---
  swagger: "2.0"
  info:
    title: "False Catcher"
    description: "False Catcher"
    version: "1.0.0"
  host: localhost:9000
  schemes:
    - "http"
    - "https"
  consumes:
    - application/json
  produces:
    - application/json