---
  swagger: "2.0"
  info:
    title: "False Catcher"
    description: "False Catcher"
    version: "1.0.0"
  #host: wl-legio-47.avp.ru:9000
  host: localhost:9000
  schemes:
    - "http"
  consumes:
    - application/json
  produces:
    - application/json